services:
  database-mysql:
    container_name: database-mysql
    hostname: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inzynier
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '4306:3306'
  database-mongodb:
    container_name: database-mongodb
    hostname: mongo
    image: mongo:5.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
  database-postgres:
        container_name: database-postgres
        hostname: postgres
        image: postgres:9.6.24
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB= inzynier
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
  python-connect:
    container_name: python-connect
    image: python:3.9.10
    command: bash -c "pip install mysql-connector-python && pip install flask && tail -F anything "
    ports:
      - '5000:5000'
    volumes:
      - ./:/app